language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
#  - nightly

install:
  - composer install
  - cp tests/ftests/config.php.dist tests/ftests/config.php
script: vendor/bin/phpunit --coverage-text tests/utests
env:
  secure: ekhDBZcfLatzXVYEumYKXWhQvA+eBP+RrVkNSrZ3tw33ZvfabmQtF5CNTmko5Ln4tv4eDjk5mxVICbfX3+4KpeE9YYvgrhSE7clHuabKKDmVJV2PYiT8vHsQqBZ0q0vQPC+mj0Bh+F6tXDfPJ0LRDKzwlKpGFzDUZjthQzzCKQ0=

