language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
#  - nightly

install:
  - curl -L -o phpunit https://phar.phpunit.de/phpunit-7.phar
  - chmod +x phpunit
  - cp tests/ftests/config.php.dist tests/ftests/config.php
script: ./phpunit

